Core data cr impl
SergeyBindasov/test pull request #16
Opened 2022-02-16 16:46 UTC by SergeyBindasov

2022-02-18 06:25 UTC, denisnzrk requested changes

2022-02-18 06:25 UTC, denisnzrk commented on Navigation/Models/PostDataModel.swift
> +    let context = (UIApplication.shared.delegate as! AppDelegate).persistentContainer.viewContext
Лучше подобного избегать :)
Есть случае, когда действительно приходится залезть в AppDelegate подобным образом, но тут в этом нет необходимости.
Передайте на этапе инициализации в `init` :)

2022-02-18 07:01 UTC, SergeyBindasov commented on Navigation/Models/PostDataModel.swift
> +    let context = (UIApplication.shared.delegate as! AppDelegate).persistentContainer.viewContext
Поправил :) https://github.com/SergeyBindasov/NetologyTasks/pull/16/commits/db5b41274b4bfcf7eb31c500b7a7f6326e22f556

2022-02-19 13:30 UTC, denisnzrk approved these changes

2022-02-21 09:16 UTC, merged